import snapshotJson from "../data/ctftime-snapshot.json";

export interface CTFEvent {
	event_id: string;
	title: string;
	place: number;
	ctf_points: string;
	rating_points: number | null;
	weight: number | null;
	time: number;
}

export interface CTFTimeData {
	team: {
		name: string;
		country: string;
		rating_place: number | null;
		rating_points: number | null;
		country_place: number | null;
	};
	events: CTFEvent[];
	year: number;
	updated_at: string;
}

// Generated by scripts/sync-ctftime.mjs (CI, weekly) — baked in at build time.
const snapshot = snapshotJson as unknown as CTFTimeData;

function normalizeCTFEvent(event: CTFEvent): CTFEvent {
	return {
		event_id: String(event.event_id),
		title: String(event.title),
		place: Number(event.place),
		ctf_points: String(event.ctf_points),
		rating_points: typeof event.rating_points === "number" ? event.rating_points : null,
		weight: typeof event.weight === "number" ? event.weight : null,
		time: Number(event.time),
	};
}

export function sortCTFEventsByBestPerformance(events: CTFEvent[]): CTFEvent[] {
	return [...events].sort((a, b) => {
		const aRating = typeof a.rating_points === "number" ? a.rating_points : -1;
		const bRating = typeof b.rating_points === "number" ? b.rating_points : -1;
		if (aRating !== bRating) return bRating - aRating;

		if (a.place !== b.place) return a.place - b.place;

		const aPoints = Number.parseFloat(a.ctf_points);
		const bPoints = Number.parseFloat(b.ctf_points);
		if (!Number.isNaN(aPoints) && !Number.isNaN(bPoints) && aPoints !== bPoints) {
			return bPoints - aPoints;
		}

		if (a.time !== b.time) return b.time - a.time;
		return a.title.localeCompare(b.title);
	});
}

export function getTopCTFPerformances(events: CTFEvent[], limit = 5): CTFEvent[] {
	return sortCTFEventsByBestPerformance(events).slice(0, limit);
}

export function getCTFTimeData(): CTFTimeData {
	return {
		team: { ...snapshot.team },
		events: sortCTFEventsByBestPerformance(snapshot.events.map(normalizeCTFEvent)),
		year: snapshot.year,
		updated_at: snapshot.updated_at,
	};
}
